# Documentation
# * mdbook   https://rust-lang.github.io/mdBook/
# * template https://github.com/kg4zow/mdbook-template/

[book]
authors                 = ["Ephemeral Space Contributors"]
language                = "en"
multilingual            = false
src                     = "src"
title                   = "Ephemeral Space Development Wiki"

[output.html]
additional-css          = [ "section-lines.css" , "version-commit.css" ]
curly-quotes            = false
git-repository-url      = "https://github.com/EphemeralSpace/ephemeral-space"
no-section-label        = true
default-theme           = "coal"
preferred-dark-theme    = "coal"
title = "Ephemeral Space Development Wiki"
description = "Tutorial & reference for all Space Wizards Federation projects, including the Robust Toolbox engine and its flagship open source game, Space Station 14."
